base_url: http://localhost:11434
created_at: '2025-09-18T00:48:09.676958'
default_models:
  general: llama3.1:latest
  programming: deepseek-coder:latest
  small: phi3:latest
fallback_chain:
- deepseek-coder:latest
- codellama:latest
- llama3.1:latest
- mistral:latest
performance:
  max_tokens: 2000
  temperature: 0.7
  timeout: 60
  top_p: 0.9
version: 1.0.0
